### PR TITLE
Basic Linux Support

### PR DESCRIPTION
**Pull request by lyssieth**
A basic PR for Linux support.

Current known issues:
- Finding save games is hard-coded to only check home directory. There has to be some better way

### CODE REVIEW

**Comment by lyssieth** [comment]
This also closes #7.

**Comment by KarlitosVII** [comment]
Thank you !

**Comment by NerdHarder615** [comment]
Can you post the commands to make this for Linux? I am not having any luck creating the app. I updated the Makefile & removed .exe from cargo. Is there anything else that needs to be tweaked for Linux?

**Comment by lyssieth** [comment]
All I did was `cargo build --release` and it worked.

**Comment by NerdHarder615** [comment]
thanks, I forgot this was written in rust. I was trying to use make -f Makefile, so just personal mistake

**Pull request merged**
